POST http://localhost:8080/ HTTP/1.1
content-type: text/plain




###

POST http://localhost:8082/users HTTP/1.1
content-type: application/json

{
  "name": "Lola",
  "age": 24,
  "friends": []
}

# 201 (Created) {"id": "2"}
# 404 (Not Found)


###


POST http://localhost:8082/users HTTP/1.1
content-type: application/json

{
  "name": "Tea",
  "age": 25,
  "friends": []
}

# 201 (Created) {"id": "3"}
# 404 (Not Found)

###

PUT  http://localhost:8082/users/1/friends HTTP/1.1
content-type: application/json

{
  "target_id": 2
}

# 200 (OK)
# 404 (Not Found)

###

PUT  http://localhost:8082/users/2/friends HTTP/1.1
content-type: application/json

{
  "target_id": 3
}

# 200 (OK)
# 404 (Not Found)

###

PUT  http://localhost:8082/users/1/friends HTTP/1.1
content-type: application/json

{
  "target_id": 3
}

# 200 (OK)
# 404 (Not Found)


###


GET  http://localhost:8082/users/1/friends HTTP/1.1
content-type: application/json



# 200 (OK)
# 404 (Not Found)

###

GET  http://localhost:8082/users/2/friends HTTP/1.1
content-type: application/json



# 200 (OK)
# 404 (Not Found)

###

PATCH http://localhost:8082/users/1 HTTP/1.1
content-type: application/json

{
  "age": 33
}

# 200 (OK)
# 404 (Not Found)

###

PATCH http://localhost:8082/users/2 HTTP/1.1
content-type: application/json

{
  "age": 32
}

# 200 (OK)
# 404 (Not Found)

###

POST http://localhost:8082/users/3 HTTP/1.1
content-type: text/plain



# 200 (OK)
# 404 (Not Found)

###

DELETE http://localhost:8082/users/1 HTTP/1.1
content-type: application/json



# 200 (OK)
# 404 (Not Found)

###